### ISSUE TITLE
COCO Panoptic Answer

### ISSUE THREAD

**Issue by Yingyue-L** [SHI-Labs/VCoder#4]
I follow the description on your paper, using the OneFormer model trained on COCO with DiNAT-L backbone to obtain the segmentation map, but the results is different from the answer your provide. Can you give the code for generating the answers?

**Comment by praeclarumjj3** [comment]
Hi @Yingyue-L, thank you for your interest! Could you share the results that you obtained?

Please note that the model's outputs are non-deterministic, so you may observe different run results. You can find the snapshots for our results [here](https://github.com/SHI-Labs/VCoder/tree/main/images) -> the `demo*.png` files.

**Comment by Yingyue-L** [comment]
Thanks for your reply! Sorry, I didn't describe my question clearly. The results I can't reproduce is the panoptic problem gt answers --`playground/data/coco_segm_text/train/panoptic.txt`. I use the OneFormer model trained on COCO with DiNAT-L backbone to obtain the [panoptic_json.txt](https://drive.google.com/file/d/18jdZxx0iLiSDGryaEFSDhkWJBJZYQlBC/view?usp=sharing) as your paper describe, but I get the different answer compare with the answer your provide as shown below. So I hope you could share your code that generate the answers, I would greatly appreciate it!

**Comment by praeclarumjj3** [comment]
Hi @Yingyue-L, we modified the [demo script](https://github.com/SHI-Labs/OneFormer/tree/main/demo) from OneFormer to obtain the class names from the predictions and used the following postprocessing code to prepare our dataset. I might release the code in the future if I find the time. Please feel free to ask any other confusions you may have.

```python
def format_text(txt_output):
    if len(txt_output.keys()) == 0:
        return "There are no detectable objects in the image"
    
    if len(txt_output.keys()) == 1:
        if list(txt_output.values())[0] == 1:
            verb = "is"
            plural = ""
        else:
            verb = "are"
            plural = "s"
    else:
        verb = "are"
        plural = "s"
        
    txt_line = f"The object{plural} present in the image {verb}:"
    for k in txt_output.keys():
        num = "" if txt_output[k][0] == 1 else p.number_to_words(txt_output[k][0]) + " "
        noun = k.split('-')[0] if txt_output[k][0] == 1 else p.plural(k.split('-')[0])
        txt_line += f" {num}{noun},"
    txt_line = txt_line[:-1] + "."
    return txt_line
```

`Note:` You may have to return the class names from the [visualizer](https://github.com/SHI-Labs/OneFormer/blob/4962ef6a96ffb76a76771bfa3e8b3587f209752b/demo/visualizer.py#L570) in the demo and make changes in [predictor.py](https://github.com/SHI-Labs/OneFormer/blob/4962ef6a96ffb76a76771bfa3e8b3587f209752b/demo/predictor.py#L42).

```python
    def draw_panoptic_seg(self, panoptic_seg, segments_info, area_threshold=None, alpha=0.7):
        """
        Draw panoptic prediction annotations or results.
        Args:
            panoptic_seg (Tensor): of shape (height, width) where the values are ids for each
                segment.
            segments_info (list[dict] or None): Describe each segment in `panoptic_seg`.
                If it is a ``list[dict]``, each dict contains keys "id", "category_id".
                If None, category id of each pixel is computed by
                ``pixel // metadata.label_divisor``.
            area_threshold (int): stuff segments with less than `area_threshold` are not drawn.
        Returns:
            output (VisImage): image object with visualizations.
        """
        pred = _PanopticPrediction(panoptic_seg, segments_info, self.metadata)

        if self._instance_mode == ColorMode.IMAGE_BW:
            self.output.reset_image(self._create_grayscale_image(pred.non_empty_mask()))

        classes = []
        json = {}

        import pycocotools.mask as mask_util
        
        json = {}
        
        # draw mask for all semantic segments first i.e. "stuff"
        for mask, sinfo in pred.semantic_masks():
            category_idx = sinfo["category_id"]
            try:
                mask_color = [x / 255 for x in self.metadata.stuff_colors[category_idx]]
            except AttributeError:
                mask_color = None

            text = self.class_names[category_idx]
            classes.append(text)

            rle = mask_util.encode(np.asfortranarray(mask, dtype=np.uint8))
            rle["counts"] = rle["counts"].decode("utf-8")
            if text.split("-")[0] not in json.keys():
                json[text.split("-")[0]] = [rle]
            else:
                json[text.split("-")[0]].append(rle)

            self.draw_binary_mask(
                mask,
                color=mask_color,
                edge_color=_OFF_WHITE,
                text=text,
                alpha=alpha,
                area_threshold=area_threshold,
            )

        # draw mask for all instances second
        all_instances = list(pred.instance_masks())
        if len(all_instances) == 0:
            return self.output, {}
        masks, sinfo = list(zip(*all_instances))
        category_ids = [x["category_id"] for x in sinfo]

        try:
            scores = [x["score"] for x in sinfo]
        except KeyError:
            scores = None
        labels = _create_text_labels(
            category_ids, scores, self.class_names, [x.get("iscrowd", 0) for x in sinfo]
        )

        for mask, text in zip(masks, labels):
            rle = mask_util.encode(np.asfortranarray(mask, dtype=np.uint8))
            rle["counts"] = rle["counts"].decode("utf-8")
            if text.split("-")[0] not in json.keys():
                json[text.split("-")[0]] = [rle]
            else:
                json[text.split("-")[0]].append(rle)

        classes.extend(labels)
        texts = {}
        for text in classes:
            if text not in texts.keys():
                texts[text] = [1, "thing" if text in self.thing_classes else "stuff"]
            else:
                texts[text][0] += 1

        try:
            colors = [
                self._jitter([x / 255 for x in self.metadata.stuff_colors[c]]) for c in category_ids
            ]
        except AttributeError:
            colors = None
        self.overlay_instances(masks=masks, labels=labels, assigned_colors=colors, alpha=alpha)

        return self.output, texts, json
```

**Comment by Yingyue-L** [comment]
Thanks for your so detailed reply! I'm confused that the predictions I got is different from the answer your provided, not only the number of class but also the number of the specific class, such as chairs, person and so on. I also use the `demo.py` to generate the results.

**Comment by Yingyue-L** [comment]
Thank for your detailed reply! I try to use the code you provide to reproduce the answer, but I got the different results compared with the answer you privode. Can you give me the `demo.py` you used ?
![image](https://github.com/SHI-Labs/VCoder/assets/56422335/6b87ebcb-7826-40a6-a1ea-e4f9ad3aa1ad)

**Comment by praeclarumjj3** [comment]
Hi @Yingyue-L, could you share the image from COCO that you are using?

Here's the demo.py (same as in the OneFormer repo apart from the part that writes the results to a text file) that we used to create our training and validation set using COCO images:

```python
import argparse
import multiprocessing as mp
import os
import torch
import random
# fmt: off
import sys
sys.path.insert(1, os.path.join(sys.path[0], '..'))
# fmt: on

import time
import cv2
import numpy as np
import tqdm
import glob

from detectron2.config import get_cfg
from detectron2.data.detection_utils import read_image
from detectron2.projects.deeplab import add_deeplab_config
from detectron2.utils.logger import setup_logger

from oneformer import (
    add_oneformer_config,
    add_common_config,
    add_oneformer_config,
    add_common_config,
    add_swin_config,
    add_dinat_config,
    add_convnext_config,
)
from predictor import VisualizationDemo
from colormap import random_color
from detectron2.data import MetadataCatalog
import inflect
import math

def split_list(lst, n):
    """Split a list into n (roughly) equal-sized chunks"""
    chunk_size = math.ceil(len(lst) / n)  # integer division
    return [lst[i:i+chunk_size] for i in range(0, len(lst), chunk_size)]


def get_chunk(lst, n, k):
    chunks = split_list(lst, n)
    return chunks[k]



import warnings
warnings.filterwarnings("ignore")
 
 
# Declare method of inflect module
p = inflect.engine()

# constants
WINDOW_NAME = "OneFormer Demo"

def setup_cfg(args):
    # load config from file and command-line arguments
    cfg = get_cfg()
    add_deeplab_config(cfg)
    add_common_config(cfg)
    add_swin_config(cfg)
    add_dinat_config(cfg)
    add_convnext_config(cfg)
    add_oneformer_config(cfg)
    cfg.merge_from_file(args.config_file)
    cfg.merge_from_list(args.opts)
    cfg.freeze()
    return cfg


def merge_json(args):
    results = {}
    for task in ["semantic", "instance", "panoptic"]:
        results[task] = {}
        for idx in range(args.num_chunks):
            with open(f'{args.output}/{task}/{args.num_chunks}_{idx}.json', 'r') as infile:
                results[task] = {**results[task], **json.load(infile)}
    with open(f'{args.output}/{task}.json', 'w') as output_file:
        json.dump(results, output_file)

def get_parser():
    parser = argparse.ArgumentParser(description="oneformer demo for builtin configs")
    parser.add_argument(
        "--config-file",
        default="../configs/ade20k/swin/oneformer_swin_large_IN21k_384_bs16_160k.yaml",
        metavar="FILE",
        help="path to config file",
    )
    parser.add_argument("--task", help="Task type")
    parser.add_argument(
        "--input",
        type=str,
        help="folder",
    )
    parser.add_argument(
        "--stuff-class-names",
        nargs="*",
        default=[],
        help="A list of user-defined stuff class_names"
    )
    parser.add_argument(
        "--thing-class-names",
        nargs="*",
        default=[],
        help="A list of user-defined thing class_names"
    )
    parser.add_argument(
        "--output",
        help="A file or directory to save output visualizations. "
        "If not given, will show output in an OpenCV window.",
    )
    parser.add_argument("--num-chunks", type=int, default=1)
    parser.add_argument("--chunk-idx", type=int, default=0)

    parser.add_argument(
        "--confidence-threshold",
        type=float,
        default=0.5,
        help="Minimum score for instance predictions to be shown",
    )
    parser.add_argument(
        "--opts",
        help="Modify config options using the command-line 'KEY VALUE' pairs",
        default=[],
        nargs=argparse.REMAINDER,
    )
    return parser

def format_text(txt_output):
    if len(txt_output.keys()) == 0:
        return "There are no detectable objects in the image", "There are no detectable objects in the image"
    
    if len(txt_output.keys()) == 1:
        if list(txt_output.values())[0] == 1:
            verb = "is"
            plural = ""
        else:
            verb = "are"
            plural = "s"
    else:
        verb = "are"
        plural = "s"
        
    txt_line = f"The object{plural} present in the image {verb}:"
    txt_line_region = f"The object{plural} present in the image {verb}:"
    for k in txt_output.keys():
        num = "" if txt_output[k][0] == 1 else p.number_to_words(txt_output[k][0]) + " "
        noun = k.split('-')[0] if txt_output[k][0] == 1 else p.plural(k.split('-')[0])
        txt_line += f" {num}{noun},"
        txt_line_region += f" <{txt_output[k][1]}>{num}{noun}</{txt_output[k][1]}>,"
    # txt_line = txt_line[:-1] + ".</s>"
    txt_line = txt_line[:-1] + "."
    txt_line_region = txt_line_region[:-1] + "."
    return txt_line, txt_line_region

if __name__ == "__main__":
    seed = 0
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

    mp.set_start_method("spawn", force=True)
    args = get_parser().parse_args()
    setup_logger(name="fvcore")
    logger = setup_logger()
    logger.info("Arguments: " + str(args))

    cfg = setup_cfg(args)

    tasks = ["panoptic", "semantic", "instance"]

    os.makedirs(args.output, exist_ok=True)
    demo = VisualizationDemo(cfg, parallel=True, is_open=False)
    pan_json = {}
    sem_json = {}

    if args.input:
        paths = glob.glob(f'{args.input}/*.jpg')
        paths = get_chunk(paths, args.num_chunks, args.chunk_idx)
        
        for path in tqdm.tqdm(paths, disable=not args.output):
            # use PIL, to be consistent with evaluation
            img = read_image(path, format="BGR")
            start_time = time.time()
            predictions, visualized_output, txt_output, json_output = demo.run_on_image(img, args.task, None)
            logger.info(
                "{}: {} in {:.2f}s".format(
                    path,
                    "detected {} instances".format(len(predictions["instances"]))
                    if "instances" in predictions
                    else "finished",
                    time.time() - start_time,
                )
            )

            if args.output:                    
                for k in visualized_output.keys():
                    opath = os.path.join(args.output, k)    
                    os.makedirs(opath, exist_ok=True)
                    out_filename = os.path.join(opath, os.path.basename(path))
                    visualized_output[k].save(out_filename)
                    
                for k in txt_output.keys():
                    txt_line = format_text(txt_output[k])
                    with open(f'{args.output}/{k.split("_")[0]}.txt', 'a') as f:
                        f.write(f'<IMG>{path.split("/")[-1]}<IMG>')
                        f.write(f'{txt_line}')
                        f.write(f"\n")
            else:
                raise ValueError("Please specify an output path!")
    else:
        raise ValueError("No Input Given")
```

**Comment by Yingyue-L** [comment]
> Hi @Yingyue-L, could you share the image from COCO that you are using?
> 
> Here's the demo.py (same as in the OneFormer repo apart from the part that writes the results to a text file) that we used to create our training and validation set using COCO images:
> 
> ```python
> import argparse
> import multiprocessing as mp
> import os
> import torch
> import random
> # fmt: off
> import sys
> sys.path.insert(1, os.path.join(sys.path[0], '..'))
> # fmt: on
> 
> import time
> import cv2
> import numpy as np
> import tqdm
> import glob
> 
> from detectron2.config import get_cfg
> from detectron2.data.detection_utils import read_image
> from detectron2.projects.deeplab import add_deeplab_config
> from detectron2.utils.logger import setup_logger
> 
> from oneformer import (
>     add_oneformer_config,
>     add_common_config,
>     add_oneformer_config,
>     add_common_config,
>     add_swin_config,
>     add_dinat_config,
>     add_convnext_config,
> )
> from predictor import VisualizationDemo
> from colormap import random_color
> from detectron2.data import MetadataCatalog
> import inflect
> import math
> 
> def split_list(lst, n):
>     """Split a list into n (roughly) equal-sized chunks"""
>     chunk_size = math.ceil(len(lst) / n)  # integer division
>     return [lst[i:i+chunk_size] for i in range(0, len(lst), chunk_size)]
> 
> 
> def get_chunk(lst, n, k):
>     chunks = split_list(lst, n)
>     return chunks[k]
> 
> 
> 
> import warnings
> warnings.filterwarnings("ignore")
>  
>  
> # Declare method of inflect module
> p = inflect.engine()
> 
> # constants
> WINDOW_NAME = "OneFormer Demo"
> 
> def setup_cfg(args):
>     # load config from file and command-line arguments
>     cfg = get_cfg()
>     add_deeplab_config(cfg)
>     add_common_config(cfg)
>     add_swin_config(cfg)
>     add_dinat_config(cfg)
>     add_convnext_config(cfg)
>     add_oneformer_config(cfg)
>     cfg.merge_from_file(args.config_file)
>     cfg.merge_from_list(args.opts)
>     cfg.freeze()
>     return cfg
> 
> 
> def merge_json(args):
>     results = {}
>     for task in ["semantic", "instance", "panoptic"]:
>         results[task] = {}
>         for idx in range(args.num_chunks):
>             with open(f'{args.output}/{task}/{args.num_chunks}_{idx}.json', 'r') as infile:
>                 results[task] = {**results[task], **json.load(infile)}
>     with open(f'{args.output}/{task}.json', 'w') as output_file:
>         json.dump(results, output_file)
> 
> def get_parser():
>     parser = argparse.ArgumentParser(description="oneformer demo for builtin configs")
>     parser.add_argument(
>         "--config-file",
>         default="../configs/ade20k/swin/oneformer_swin_large_IN21k_384_bs16_160k.yaml",
>         metavar="FILE",
>         help="path to config file",
>     )
>     parser.add_argument("--task", help="Task type")
>     parser.add_argument(
>         "--input",
>         type=str,
>         help="folder",
>     )
>     parser.add_argument(
>         "--stuff-class-names",
>         nargs="*",
>         default=[],
>         help="A list of user-defined stuff class_names"
>     )
>     parser.add_argument(
>         "--thing-class-names",
>         nargs="*",
>         default=[],
>         help="A list of user-defined thing class_names"
>     )
>     parser.add_argument(
>         "--output",
>         help="A file or directory to save output visualizations. "
>         "If not given, will show output in an OpenCV window.",
>     )
>     parser.add_argument("--num-chunks", type=int, default=1)
>     parser.add_argument("--chunk-idx", type=int, default=0)
> 
>     parser.add_argument(
>         "--confidence-threshold",
>         type=float,
>         default=0.5,
>         help="Minimum score for instance predictions to be shown",
>     )
>     parser.add_argument(
>         "--opts",
>         help="Modify config options using the command-line 'KEY VALUE' pairs",
>         default=[],
>         nargs=argparse.REMAINDER,
>     )
>     return parser
> 
> def format_text(txt_output):
>     if len(txt_output.keys()) == 0:
>         return "There are no detectable objects in the image", "There are no detectable objects in the image"
>     
>     if len(txt_output.keys()) == 1:
>         if list(txt_output.values())[0] == 1:
>             verb = "is"
>             plural = ""
>         else:
>             verb = "are"
>             plural = "s"
>     else:
>         verb = "are"
>         plural = "s"
>         
>     txt_line = f"The object{plural} present in the image {verb}:"
>     txt_line_region = f"The object{plural} present in the image {verb}:"
>     for k in txt_output.keys():
>         num = "" if txt_output[k][0] == 1 else p.number_to_words(txt_output[k][0]) + " "
>         noun = k.split('-')[0] if txt_output[k][0] == 1 else p.plural(k.split('-')[0])
>         txt_line += f" {num}{noun},"
>         txt_line_region += f" <{txt_output[k][1]}>{num}{noun}</{txt_output[k][1]}>,"
>     # txt_line = txt_line[:-1] + ".</s>"
>     txt_line = txt_line[:-1] + "."
>     txt_line_region = txt_line_region[:-1] + "."
>     return txt_line, txt_line_region
> 
> if __name__ == "__main__":
>     seed = 0
>     random.seed(seed)
>     np.random.seed(seed)
>     torch.manual_seed(seed)
>     torch.cuda.manual_seed_all(seed)
>     torch.backends.cudnn.deterministic = True
>     torch.backends.cudnn.benchmark = False
> 
>     mp.set_start_method("spawn", force=True)
>     args = get_parser().parse_args()
>     setup_logger(name="fvcore")
>     logger = setup_logger()
>     logger.info("Arguments: " + str(args))
> 
>     cfg = setup_cfg(args)
> 
>     tasks = ["panoptic", "semantic", "instance"]
> 
>     os.makedirs(args.output, exist_ok=True)
>     demo = VisualizationDemo(cfg, parallel=True, is_open=False)
>     pan_json = {}
>     sem_json = {}
> 
>     if args.input:
>         paths = glob.glob(f'{args.input}/*.jpg')
>         paths = get_chunk(paths, args.num_chunks, args.chunk_idx)
>         
>         for path in tqdm.tqdm(paths, disable=not args.output):
>             # use PIL, to be consistent with evaluation
>             img = read_image(path, format="BGR")
>             start_time = time.time()
>             predictions, visualized_output, txt_output, json_output = demo.run_on_image(img, args.task, None)
>             logger.info(
>                 "{}: {} in {:.2f}s".format(
>                     path,
>                     "detected {} instances".format(len(predictions["instances"]))
>                     if "instances" in predictions
>                     else "finished",
>                     time.time() - start_time,
>                 )
>             )
> 
>             if args.output:                    
>                 for k in visualized_output.keys():
>                     opath = os.path.join(args.output, k)    
>                     os.makedirs(opath, exist_ok=True)
>                     out_filename = os.path.join(opath, os.path.basename(path))
>                     visualized_output[k].save(out_filename)
>                     
>                 for k in txt_output.keys():
>                     txt_line = format_text(txt_output[k])
>                     with open(f'{args.output}/{k.split("_")[0]}.txt', 'a') as f:
>                         f.write(f'<IMG>{path.split("/")[-1]}<IMG>')
>                         f.write(f'{txt_line}')
>                         f.write(f"\n")
>             else:
>                 raise ValueError("Please specify an output path!")
>     else:
>         raise ValueError("No Input Given")
> ```

Thanks for your reply! The image I used is the `000000000139.jpg` on the val set as shown below.
![000000000139](https://github.com/SHI-Labs/VCoder/assets/56422335/4a55ca4c-4d2c-4c98-9426-40eb06eb9703)

**Comment by Yingyue-L** [comment]
Hi @praeclarumjj3, Sorry to bother you. Do you have some idea about my question now ?

**Comment by praeclarumjj3** [comment]
Hi @Yingyue-L, I'm sorry I forgot to reply. I tried running the image you shared through our data gen script, and the result matches the one we released in the COST dataset. Did you set the seed as `0`, as mentioned in the demo.py script I shared earlier?

Also, what GPU are you using, and what are your environment specifications? I suggest setting the environment according to [official guidelines](https://github.com/SHI-Labs/OneFormer/blob/main/INSTALL.md#requirements) in OneFormer (as we used that one). We processed the dataset by splitting the dataset across 8 A100 GPUs.

**Comment by Yingyue-L** [comment]
> Hi @Yingyue-L, I'm sorry I forgot to reply. I tried running the image you shared through our data gen script, and the result matches the one we released in the COST dataset. Did you set the seed as `0`, as mentioned in the demo.py script I shared earlier?
> 
> Also, what GPU are you using, and what are your environment specifications? I suggest setting the environment according to [official guidelines](https://github.com/SHI-Labs/OneFormer/blob/main/INSTALL.md#requirements) in OneFormer (as we used that one). We processed the dataset by splitting the dataset across 8 A100 GPUs.

Thanks for your reply ! I already set the `seed=0`, and set the environment as the official guidelines. The GPU I used is the 1 3090.

**Comment by Yingyue-L** [comment]
> > Hi @Yingyue-L, I'm sorry I forgot to reply. I tried running the image you shared through our data gen script, and the result matches the one we released in the COST dataset. Did you set the seed as `0`, as mentioned in the demo.py script I shared earlier?
> > Also, what GPU are you using, and what are your environment specifications? I suggest setting the environment according to [official guidelines](https://github.com/SHI-Labs/OneFormer/blob/main/INSTALL.md#requirements) in OneFormer (as we used that one). We processed the dataset by splitting the dataset across 8 A100 GPUs.
> 
> Thanks for your reply ! I already set the `seed=0`, and set the environment as the official guidelines. The GPU I used is the 1 3090.

Can you share the entire `demo` folder that you using now and the scripts you run the `demo.py` ?

**Comment by Yingyue-L** [comment]
Hi, @praeclarumjj3. Can you share the entire `demo` folder that you using now, the scripts you run the `demo.py` and the checkpoint you used ?

**Comment by Yingyue-L** [comment]
Hi, @praeclarumjj3, I really need your help. Could you please share your complete code and checkpoint with me when you have time?

**Comment by praeclarumjj3** [comment]
Hi @Yingyue-L, apologies for the delay. I have been busy. Please find the demo folder (zipped) attached [d.zip](https://github.com/SHI-Labs/VCoder/files/14675881/d.zip).

We used the publicly available checkpoint found on the OneFormer repo: https://shi-labs.com/projects/oneformer/coco/150_16_dinat_l_oneformer_coco_100ep.pth

I would also recommend comparing results for other images. It is not uncommon for the model outputs to be slightly different on different GPUs. Another point is that we split the dataset across 8 GPUs during our dataset preparation, which can also affect the model outputs.

**Comment by Yingyue-L** [comment]
> Hi @Yingyue-L, apologies for the delay. I have been busy. Please find the demo folder (zipped) attached [d.zip](https://github.com/SHI-Labs/VCoder/files/14675881/d.zip).
> 
> We used the publicly available checkpoint found on the OneFormer repo: https://shi-labs.com/projects/oneformer/coco/150_16_dinat_l_oneformer_coco_100ep.pth
> 
> I would also recommend comparing results for other images. It is not uncommon for the model outputs to be slightly different on different GPUs. Another point is that we split the dataset across 8 GPUs during our dataset preparation, which can also affect the model outputs.

Thank you for your reply! I have tried using the code you provided and checked the results together. I found that although there are some slightly different answers, the influence is minimal.
