### ISSUE TITLE
questions.py

### ISSUE THREAD

**Issue by RussRobin** [SHI-Labs/VCoder#7]
Hi, great thanks for your wonderful work.

May you please update the link for questions.py https://huggingface.co/datasets/shi-labs/COST/blob/main/vcoder_llava/questions.py as mentioned in https://huggingface.co/datasets/shi-labs/COST, since the link now leads to 404 error?

Great thanks in advance.

**Comment by praeclarumjj3** [comment]
Hi @RussRobin, thanks for your interest and pointing this out. The path in the dataset card on HF was wrong. I have fixed the issue and it should be working now.

**Comment by RussRobin** [comment]
Thank you for your reply. I'll close this issue.
